name: GitHub-Profile-3D-Contrib

on:
  schedule: # 18:00 Tehran == 14:30 UTC
    - cron: "30 14 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ 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 }}
          USERNAME: ${{ https://github.com/kourosh07/kourosh07 }}
      - name: Commit & Push
        run: |
          git config user.name kourosh07
          git config user.email kourosh2004rahimi@gmail.com
          git add -A .
          git commit -m "update profile"
          git push
